version: '3'
services:
  api:
    container_name: api 
    build:
      context: ../net-http  # Use the current directory as the build context
      dockerfile: ./Dockerfile  # Path to your Dockerfile
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 128M
    ports:
      - "8080:8080"  # Expose your API on port 8080

  k6:
    image: grafana/k6
    volumes:
      - ../k6:/tests  # Mount your k6 test scripts directory
    command: run /tests/load-test.js  # Adjust the path to your k6 test script
